In [1]:
import numpy as np

In [83]:
Z = np.array([[ 0.5,  -0.5],
              [ 0.1, -0.3],
              [-0.2,  0.2]])

In [84]:
W = np.array([[ 0.5],
              [-0.1],
              [ 0.3]])

In [85]:
x = np.array([[1.2, 2.5, 1]])

In [86]:
U = x.dot(Z)
H = np.tanh(x.dot(Z))
Haug = np.concatenate((H, np.array([[1]])), 1)

In [87]:
O = Haug.dot(W)
Yhat = O
Yhat

array([[0.66761039]])

In [88]:
y2 = np.array([[3]])

In [89]:
e2 = y2-Yhat

In [90]:
flinhaO = 1
deltaO = flinhaO * e2
deltaO

array([[2.33238961]])

In [91]:
eta = 0.1
deltaW = eta*Haug.T.dot(deltaO)

In [92]:
deltaW

array([[ 0.13333571],
       [-0.19073211],
       [ 0.23323896]])

In [93]:
W2 = W+deltaW

In [94]:
W2

array([[ 0.63333571],
       [-0.29073211],
       [ 0.53323896]])

In [95]:
Wm3 = np.delete(W, 2, axis=0)

In [96]:
eh = deltaO.dot(Wm3.T)
flinhaU = (1/np.cosh(U))**2
deltaU = flinhaU * eh
eh

array([[ 1.1661948 , -0.23323896]])

In [97]:
deltaZ = eta*x.T.dot(deltaU)
deltaZ

array([[ 0.09420896, -0.00927204],
       [ 0.19626868, -0.01931675],
       [ 0.07850747, -0.0077267 ]])

In [98]:
Zx2 = Z+deltaZ
Zx2

array([[ 0.59420896, -0.50927204],
       [ 0.29626868, -0.31931675],
       [-0.12149253,  0.1922733 ]])